<Project Sdk="Microsoft.NET.Sdk">

  <Target Name="ValidateRequiredFiles" BeforeTargets="Build">
	  <ItemGroup>
	    <!-- <RequiredFiles Include="" /> -->
	  </ItemGroup> 
  </Target>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);PERF_PROFILE</DefineConstants>
	  <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
	  <!-- <IsAotCompatible>true</IsAotCompatible>
	  <EnableAotAnalyzer>true</EnableAotAnalyzer> -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="fyers-api-v3" Version="1.5.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="upstox-dotnet-sdk" Version="2.6.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="NewFolder\" />
  </ItemGroup>

</Project>
