import { safeRead, safeWrite } from '../helpers/fs.helper.js';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const offsetPath        = path.resolve(__dirname, '../../runtime/shm-offsets.json');
const layoutPath        = path.resolve(__dirname, '../../Config/shm-layout.json');
const nodeBufferHeader  = path.join(__dirname, '../bridge/headers/shm-buffer.hpp');
const cppBufferHeader   = path.join(__dirname, '../../03_Core_Cpp/headers/shm-buffer.hpp');

const layout = JSON.parse(safeRead(layoutPath));

// char32 is the only special token — everything else is a literal C++ type name.
const BYTE_SIZE = { double: 8, int64_t: 8, int32_t: 4, char32: 32 };

function fieldLine(name, type, count = 1) {
    if (type === 'char32') return `    char ${name}[32]{};\n`;
    if (count > 1)         return `    std::array<${type.includes('_') ? 'std::' : ''}${type}, ${count}> ${name}{};\n`;
    if (type.includes('_'))return `    std::${type} ${name}{};\n`;
    return                        `    ${type} ${name}{};\n`;
}

function fieldSize(type, count = 1) {
    const b = BYTE_SIZE[type];
    if (b === undefined) throw new Error(`[NODE] Unknown type: "${type}"`);
    return b * count;
}

function walkFields(fields) {
    let cpp = '';
    const offsets = {};
    let byte = 0;

    for (const [name, type, count = 1] of fields) {
        cpp += fieldLine(name, type, count);
        offsets[name] = byte;
        byte += fieldSize(type, count);
    }
    return { cpp, offsets, bytesPerSlot: byte };
}

function buildSection(key, section) {
    const structName = `${key[0]}${key.slice(1).toLowerCase()}Header`;
    const { cpp, offsets, bytesPerSlot } = walkFields(section.fields);
    const allOffsets = { ...offsets, __bytesPerSlot: bytesPerSlot };

    if (section.slots) allOffsets.slots = section.slots;
    return { cpp: `struct ${structName} {\n${cpp}};\n\n`, offsets: allOffsets, structName };
}

function buildOrder(key, section) {
    const structName = `${key[0]}${key.slice(1).toLowerCase()}Header`;
    const legFields  = Array.from({ length: section.maxLegs }, (_, i) =>
        section.leg.map(([name, type, count]) => [`leg${i}_${name}`, type, count])
    ).flat();

    const { cpp, offsets, bytesPerSlot } = walkFields([...section.header, ...legFields]);

    return {
        cpp: `struct ${structName} {\n${cpp}};\n\n`,
        offsets: { ...offsets, __bytesPerSlot: bytesPerSlot, __maxLegs: section.maxLegs },
        structName,
    };
}

function headerGenerator() {
    let hpp = `// AUTO-GENERATED by headerGenerator.js - DO NOT EDIT\n`;
    hpp    += `// Source of truth: Config/shm-layout.json\n\n`;
    hpp    += `#ifndef BUFFER_HEADERS_H\n#define BUFFER_HEADERS_H\n\n`;
    hpp    += `#include <cstdint>\n#include <array>\n\n`;
    hpp    += `#pragma pack(push, 1)\n\n`;

    const allOffsets = {};
    const asserts    = [];
    
    for (const [key, section] of Object.entries(layout)) {

        const { cpp, offsets, structName } = section.leg
            ? buildOrder(key, section)
            : buildSection(key, section);

        hpp += cpp;
        allOffsets[key] = offsets;
        asserts.push({ structName, bytes: offsets.__bytesPerSlot });
    }

    hpp += `#pragma pack(pop)\n\n`;
    hpp += `// Layout size constants — re-run headerGenerator.js if any assert fails\n`;

    for (const { structName, bytes } of asserts) {
        hpp += `static_assert(sizeof(${structName}) == ${bytes},\n    "Layout mismatch: ${structName} - re-run headerGenerator.js and rebuild");\n`;
    }
    hpp += `#endif // BUFFER_HEADERS_H`;

    safeWrite(nodeBufferHeader, hpp);
    safeWrite(cppBufferHeader, hpp);
    safeWrite(offsetPath, JSON.stringify(allOffsets, null, 4));
}

export default headerGenerator;