import { safeRead, safeWrite } from '../helpers/fs.helper.js';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const offsetPath        = path.resolve(__dirname, '../../runtime/shm-offsets.json');
const layoutPath        = path.resolve(__dirname, '../../Config/shm-layout.json');
const nodeBufferHeader  = path.join(__dirname, '../bridge/headers/shm-buffer.hpp');
const cppBufferHeader   = path.join(__dirname, '../../03_Core_Cpp/headers/shm-buffer.hpp');

const layout = JSON.parse(safeRead(layoutPath));

function isStructured(section) {
    return !Array.isArray(section);
}

// Flat section ( CONTROLLER, INDICES, OPTIONS )
function buildFlatStruct(name, fields) {
    const type = (name === 'CONTROLLER') ? 'int' : 'double';
    const structName = name.charAt(0) + name.slice(1).toLowerCase();
    let cpp = `struct ${structName}Header {\n`;
    fields.forEach(f => { cpp += `  ${type} ${f}{};\n`; });
    cpp += `};\n\n`;
    return cpp;
}

// Structured section ( TBTDEPTHDATA ) typed regions + array support
function buildStructuredStruct(name, section) {
    const structName = name.charAt(0) + name.slice(1).toLowerCase();
    let cpp = `struct ${structName}Header {\n`;

    if (section.double)
        section.double.forEach(f => { cpp += `  double ${f}{};\n`; });

    if (section.double_array)
        Object.entries(section.double_array).forEach(([f, n]) => {
            cpp += `  std::array<double, ${n}> ${f}{};\n`;
        });

    if (section.int64)
        section.int64.forEach(f => { cpp += `  std::int64_t ${f}{};\n`; });

    if (section.int32)
        section.int32.forEach(f => { cpp += `  std::int32_t ${f}{};\n`; });

    if (section.int32_array)
        Object.entries(section.int32_array).forEach(([f, n]) => {
            cpp += `  std::array<std::int32_t, ${n}> ${f}{};\n`;    
        });

    cpp += `};\n\n`;
    return cpp;
}

// Compute byte offsets for every field in a structured section.
// Returns { fieldName: byteOffset, ... } — also includes array base offsets.
function computeOffsets(section) {
    const offsets = {};
    let byte = 0;

    function add(name, byteSize, count = 1) {
        offsets[name] = byte;
        byte += byteSize * count;
    }

    (section.double     ?? []).forEach(f => add(f, 8));
    Object.entries(section.double_array ?? {}).forEach(([f, n]) => add(f, 8, n));
    (section.int64      ?? []).forEach(f => add(f, 8));
    (section.int32      ?? []).forEach(f => add(f, 4));
    Object.entries(section.int32_array ?? []).forEach(([f, n]) => add(f, 4, n));

    offsets.__bytesPerSlot = byte;
    return offsets;
}

function headerGenerator() {
    let hpp = `// AUTO-GENERATED by headerGenerator.js - DO NOT EDIT\n`;
    hpp    += `// Source of truth: Config/shm-layout.json\n\n`;
    hpp    += `#ifndef BUFFER_HEADERS_H\n#define BUFFER_HEADERS_H\n\n`;
    hpp    += `#include <cstdint>\n`;
    hpp    += `#include <array>\n\n`;

    const allOfsets = {};
    
    for (const [key, section] of Object.entries(layout)) {
        if(isStructured(section)) {
            hpp += buildStructuredStruct(key, section);

            allOfsets[key] = {
                slots: section.slots ?? 1,
                ...computeOffsets(section),
            };
        } else {
            hpp += buildFlatStruct(key, section);
        }
    }
    hpp += `#endif // BUFFER_HEADERS_H`;

    safeWrite(nodeBufferHeader, hpp);
    safeWrite(cppBufferHeader, hpp);
    safeWrite(offsetPath, JSON.stringify(allOfsets, null, 4));
}

export default headerGenerator;