import { safeRead, safeWrite } from '../helpers/fs.helper.js';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const layoutPath = path.resolve(__dirname, '../../Config/shm-layout.json');
const layout = JSON.parse(safeRead(layoutPath, 'utf8'));

const nodeBufferHeader = path.join(__dirname, '../bridge/headers/shm-buffer.hpp');
const cppBufferHeader = path.join(__dirname, '../../03_Core_Cpp/headers/shm-buffer.hpp');

export default async function headerGenerator() {
    let hppContent = `// AUTO-GENERATED by headerGenerator.js - DO NOT EDIT\n// Source of truth: Config/shm-layout.json\n\n#ifndef BUFFER_HEADERS_H\n#define BUFFER_HEADERS_H\n\n`;
    
    for (const [key, fields] of Object.entries(layout)) {
        const structName = key.charAt(0) + key.slice(1).toLowerCase();
        const type = (key === "CONTROLLER") ? "int" : "double";
    
        hppContent += `struct ${structName}BufferHeader {\n`;
        fields.forEach(field => {
            hppContent += `    ${type} ${field};\n`;
        });
        hppContent += `};\n\n`;
    }

    hppContent += `#endif // BUFFER_HEADER_H`;
    safeWrite(nodeBufferHeader, hppContent, 'utf8');
    safeWrite(cppBufferHeader, hppContent, 'utf8');
}
