struct TradeData {
    double instrument;
    double ltp;
    double volume;
    double oi;
    double chngInOi;
    double totBuyQty;
    double totSellQty;
    double avgTradePrice;
    double high;
    double low;
    double open;
    double prevClose;
    double upperCkt;
    double lowerCkt;
    double exchFeedTime;
    double ch;
    double chp;
    double signal;
    double action;
};