// AUTO-GENERATED by headerGenerator.js - DO NOT EDIT
// Source of truth: Config/shm-layout.json

#ifndef BUFFER_HEADERS_H
#define BUFFER_HEADERS_H

#include <cstdint>
#include <array>

struct ControllerHeader {
  int systemStatus{};
  int IndicesCount{};
  int OptionsCount{};
  int tbtSocketSymbolCount{};
  int apiSymbolCount{};
  int signal{};
  int action{};
};

struct IndicsHeader {
  double instrument{};
  double ltp{};
  double exchFeedTime{};
  double high{};
  double low{};
  double open{};
  double prevClose{};
  double ch{};
  double chp{};
  double signal{};
  double action{};
};

struct OptionsHeader {
  double instrument{};
  double cp{};
  double ltp{};
  double volume{};
  double oi{};
  double chngInOi{};
  double totBuyQty{};
  double totSellQty{};
  double avgTradePrice{};
  double high{};
  double low{};
  double open{};
  double prevClose{};
  double upperCkt{};
  double lowerCkt{};
  double exchFeedTime{};
  double ch{};
  double chp{};
  double signal{};
  double action{};
};

struct TbtdepthdataHeader {
  std::array<double, 50> bidPrice{};
  std::array<double, 50> askPrice{};
  std::int64_t tbq{};
  std::int64_t tsq{};
  std::int64_t timestamp{};
  std::int64_t sendtime{};
  std::int32_t active{};
  std::int32_t instrument{};
  std::int32_t seqNo{};
  std::array<std::int32_t, 50> bidqty{};
  std::array<std::int32_t, 50> askqty{};
  std::array<std::int32_t, 50> bidord{};
  std::array<std::int32_t, 50> askord{};
};

#endif // BUFFER_HEADERS_H