// AUTO-GENERATED by headerGenerator.js - DO NOT EDIT
// Source of truth: Config/shm-layout.json

#ifndef BUFFER_HEADERS_H
#define BUFFER_HEADERS_H

#include <cstdint>
#include <array>

struct ControllerHeader {
  int systemStatus{};
  int IndicesCount{};
  int OptionsCount{};
  int tbtSocketSymbolCount{};
  int apiSymbolCount{};
  int signal{};
  int action{};
};

struct IndicsHeader {
  double instrument{};
  double ltp{};
  double exchFeedTime{};
  double high{};
  double low{};
  double open{};
  double prevClose{};
  double ch{};
  double chp{};
  double fp{};
  double fpch{};
  double fpchp{};
  double iVixLtp{};
  double iVixCh{};
  double iVixChp{};
  double signal{};
  double action{};
};

struct OptionsHeader {
  double instrument{};
  double cp{};
  double ltp{};
  double ch{};
  double chp{};
  double volume{};
  double oi{};
  double chngInOi{};
  double prevOi{};
  double totBuyQty{};
  double totSellQty{};
  double avgTradePrice{};
  double high{};
  double low{};
  double open{};
  double prevClose{};
  double upperCkt{};
  double lowerCkt{};
  double iv{};
  double delta{};
  double theta{};
  double gamma{};
  double vega{};
  double exchFeedTime{};
  double signal{};
  double action{};
};

struct TbtdepthdataHeader {
  std::array<double, 50> bidPrice{};
  std::array<double, 50> askPrice{};
  std::int64_t tbq{};
  std::int64_t tsq{};
  std::int64_t timestamp{};
  std::int64_t sendtime{};
  std::int32_t active{};
  std::int32_t instrument{};
  std::int32_t seqNo{};
  std::int32_t signal{};
  std::int32_t action{};
  std::array<std::int32_t, 50> bidqty{};
  std::array<std::int32_t, 50> askqty{};
  std::array<std::int32_t, 50> bidord{};
  std::array<std::int32_t, 50> askord{};
};

struct OrderHeader {
  double count{};
  double strategyId{};
  double timestamp{};
  double status{};
  double leg0_instrument{};
  double leg0_side{};
  double leg0_orderType{};
  double leg0_qty{};
  double leg0_limitPrice{};
  double leg0_stopPrice{};
  double leg0_slPrice{};
  double leg0_takeProfit{};
  double leg1_instrument{};
  double leg1_side{};
  double leg1_orderType{};
  double leg1_qty{};
  double leg1_limitPrice{};
  double leg1_stopPrice{};
  double leg1_slPrice{};
  double leg1_takeProfit{};
  double leg2_instrument{};
  double leg2_side{};
  double leg2_orderType{};
  double leg2_qty{};
  double leg2_limitPrice{};
  double leg2_stopPrice{};
  double leg2_slPrice{};
  double leg2_takeProfit{};
  double leg3_instrument{};
  double leg3_side{};
  double leg3_orderType{};
  double leg3_qty{};
  double leg3_limitPrice{};
  double leg3_stopPrice{};
  double leg3_slPrice{};
  double leg3_takeProfit{};
  double leg4_instrument{};
  double leg4_side{};
  double leg4_orderType{};
  double leg4_qty{};
  double leg4_limitPrice{};
  double leg4_stopPrice{};
  double leg4_slPrice{};
  double leg4_takeProfit{};
};

#endif // BUFFER_HEADERS_H